#!/bin/bash
destination_dir="/Backup_$(date '+%d_%m_%Y_%T')" 
arc_name="/Backup_$(date '+%d_%m_%Y_%T')"

while [ $# != 0 ]
do
	if [ "$1" == "-d" ]; then
		destination_dir=$2
		shift 
		shift 
	fi
	
	if [ "$1" == "-a" ]; then
		arc_name=$2
		shift
		shift
	fi

	

	if [ "$1" == "-e" ]; then
		shift
		while [ "$1" != "-d" ] && [ "$1" != "-a" ] && [ ! -z "$1" ]
		do
			file_extentions+=($1) 
			shift
		done
	fi
	
done

cd $HOME
mkdir -p $destination_dir
if [ -z "$file_extentions" ]; then
	find -depth -name "*" -exec cp --parent {} $destination_dir \; 2>/dev/null
else
	for i in $file_extentions
		do
		find -depth -name "*$i" -exec cp --parent {} $destination_dir \; 2>/dev/null
		done
fi 

cd $destination_dir
tar -cf $arc_name.tar $destination_dir 2>/dev/null
echo "Done"
