#!/bin/bash
if [ "$1" == "-d" ] || [ -z "$1" ]; then
	destination_dir="/Backup_$(date '+%d_%m_%Y_%T')" 
else
	destination_dir=$1	
fi 

if [ "$2" == "-d" ] || [ -z "$2" ]; then
	arc_name="/Backup_$(date '+%d_%m_%Y_%T')"
else
	arc_name=$2
fi 

shift
shift

cd $HOME
mkdir -p $destination_dir
if [ "$1" == "-a" ] || [ -z "$1" ]; then
	find -depth -name "*" -exec cp --parent {} $destination_dir \; 2>/dev/null
else
	file_extentions=($*)
	for i in $file_extentions
		do
		find -depth -name "*$i" -exec cp --parent {} $destination_dir \; 2>/dev/null
	done
fi 

cd $destination_dir
tar -cf $arc_name.tar $destination_dir 2>/dev/null
echo "Done"
